server {
    listen 80;
    server_name _;

    # Servir arquivos estáticos (STATIC_ROOT)
    location /static/ {
        alias /app/staticfiles/;
        # cache estáticos por 30 dias
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Servir mídia
    location /media/ {
        alias /app/media/;
        expires 7d;
    }

    # Proxy pass para a aplicação Django em 'web'
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host ;
        proxy_set_header X-Real-IP ;
        proxy_set_header X-Forwarded-For ;
        proxy_set_header X-Forwarded-Proto ;
    }

    # gzip para assets
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;
}
