# Generated by Django 4.2.7 on 2025-10-16 05:02

import apps.core.model_utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Preço",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=100, verbose_name="Categoria"),
                ),
                (
                    "estoque",
                    models.PositiveIntegerField(default=0, verbose_name="Estoque"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["-criado_em"],
            },
            bases=(apps.core.model_utils.BaseModelMixin, models.Model),
        ),
    ]
