# Generated by Django 4.2.7 on 2025-10-24 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Categoria"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(blank=True, max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Preço",
            ),
        ),
    ]
