# Generated by Django 4.2.7 on 2025-10-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail único no sistema",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
